# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: mbektasgh@outlook.com
author_name: Mehmet Bektas
has_binder: false
has_settings: true
kind: server
labextension_name: '@notebook-intelligence/notebook-intelligence'
project_short_description: Notebook Intelligence extension for JupyterLab
python_name: notebook_intelligence
repository: https://github.com/notebook-intelligence/notebook-intelligence
test: false

